### PR TITLE
feat: devnet launch

### PR DESCRIPTION
**Pull request by steph-mipt**
_Motivation_: current version of `op-up` is built for old version of `optimism`.
There's some old dockers (such `rollup-client`, instead of `op-node`), behaviors, and other small changes.

This PR contains several fixes/updates that will allow you to run devnet with the newest version of `optimism`.

PR contains a few TODOs, it would be great to get comments on them.

### CODE REVIEW

**Comment by steph-mipt** [comment]
There are some conflicts in this PR. Please provide feedback, and I'll merge the master branch into this one.

**Review by merklefruit — APPROVED** [review]
Thanks for this!

I think that most of the stuff in `/stages` will be further refactored in the future to use the `Composer` to create and orchestrate docker images instead of relying on `make` and `docker` directly. 

With regard to the `/docker` directory, it will be removed as explained in #3 in favor of component TOML configs (#14)

**Comment by steph-mipt** [comment]
That was the last fix. Thanks for the heads up regarding future refactoring.
Feel free to message me if you need any assistance with the upcoming changes in `/stages` and `/docker`.

**Comment by refcell** [comment]
Awesome, will merge - I have a ton of refactoring i already started but will rebase on top of this, thanks :)

**Pull request merged**
